# Generated by Django 4.2.20 on 2025-04-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards_app', '0001_initial'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass1', models.CharField(max_length=100)),
                ('pass2', models.CharField(max_length=100)),
                ('pass3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('assignee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_auth_app.userprofile')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boards_app.board')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth_app.userprofile')),
            ],
        ),
    ]
