# Generated by Django 4.2.20 on 2025-05-19 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0011_board_members_alter_board_owner_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pass',
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignee_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards_app.board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Done', 'Done')], default='To Do', max_length=20),
        ),
    ]
