# Generated by Django 4.2.20 on 2025-05-19 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks_app', '0002_delete_pass_alter_task_assignee_id_alter_task_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignee_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
