# Generated by Django 4.2.20 on 2025-06-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0006_remove_task_comments_comment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('lmow', 'lmow'), ('medium', 'medium'), ('high', 'high')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('review', 'review'), ('done', 'done')], default='To Do', max_length=20),
        ),
    ]
