# Generated by Django 5.2 on 2025-06-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0008_alter_task_assignee_id_alter_task_board_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
