# Generated by Django 5.2 on 2025-04-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0002_alter_board_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='owner_id',
        ),
    ]
