# Generated by Django 5.2 on 2025-04-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0004_board_owner_id'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='member_count',
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(to='user_auth_app.userprofile'),
        ),
    ]
