# Generated by Django 5.2 on 2025-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0007_remove_board_members_board_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='owner_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='tasks_high_prio_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='tasks_to_do_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='ticket_count',
            field=models.IntegerField(default=0),
        ),
    ]
