# Generated by Django 5.2 on 2025-05-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0008_alter_board_owner_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='owner_id',
        ),
    ]
