# Generated by Django 5.2 on 2025-06-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0013_alter_board_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
