# Generated by Django 5.2 on 2025-06-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0014_rename_owner_id_board_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
