# Generated by Django 5.2 on 2025-07-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0017_rename_owner_id_board_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='test',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
