# Generated by Django 5.2 on 2025-07-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0018_board_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='test',
        ),
    ]
